### ISSUE TITLE
Plot rendering still not right 

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#101]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1123544330001315600/

The forced point with non-detection is not showing on the plot. This is really young Ia, with a limit 2 days before discovery, but we are not presenting the data in a way that show this. 

The problem is there is a bogus "first detection" - but this is garbage. Needs fixed asap, we may miss very young objects because of this

**Comment by genghisken** [comment]
Yes - longstanding issue with the way my javascript code shows the non-detections.  Will fix ASAP.

**Comment by genghisken** [comment]
Finally figured it out. Not difficult, but took a while to remember how the lightcurve+javascript code works.  Fix is now rolled out on atlas4 website. It now goes back to 30 days before discovery (which is the forced photometry limit).

**Comment by genghisken** [comment]
Fixed.  Plots go back to -30 days.
