### ISSUE TITLE
 Links don't work to (at least some) NED galaxies

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#102]
I think this is a sherlock issue as the same bug on both sets of pages :

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1125036591141234300/

and

http://www.pessto.org/marshall/transients/search?q=ATLAS18pbs

In the context commentary :
"The transient is possibly associated with SDSS J125036.28+141236.8; a 22.40 mag galaxy found in the NED catalogue. It's located 1.80" S, 4.80" E from the galaxy centre."

Clicking on the link for the host galaxy SDSS J125036.28+141236.8 does not link to the NED page for the host, I get the banner error page :

"The object name that you submitted is not currently recognized
by the NED name interpreter." .......

**Comment by genghisken** [comment]
This was a Sherlock issue and is now fixed.
