### ISSUE TITLE
Add the angular distance to the transient match

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#103]
When an ATLAS transient is matched with another transient. Add a commentary text to give the angular distance. 

Something like an additional context info flag : 

Context info:  X.X arcsec from the known transient AT2018YYY 

This is because we use a large error circle matching and the transient matches are often not actually real. This causes some issues. So just reporting this separation on the page will help a lot.

**Comment by genghisken** [comment]
Done for all TNS matches.  Could easily add this for other matches as well, since the separation information is stored in the database.
