### ISSUE TITLE
On object pages  - add exact UT to the flag date

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#110]
Now that we are interested in intraday day time resolution, add the UT to the flag date "

Flag Date: June 16, 2018  

Change to : 
Flag Date : 2018 June 18 01:01 UT (MJD = 58348.04236)

**Comment by genghisken** [comment]
Ha - bad design decision 9 years ago.  The column is a 'date' field, not 'datetime' (implemented to save space) so exact date and time is currently unavailable.  I will upgrade the table when we migrate to db4, at which point all existing followup_flag_date entries will default to midnight on that day, with new ones being set correctly.

Upgrade process (as far as I can see so far) is:

* Upgrade atlas_diff_objects (1.6 billion rows in ATLAS4, 1 billion rows in ATLAS3) - including table creation script
* Upgrade Django model (web interface)
* Upgrade all database (Django) views that refer to this column
* Upgrade & recompile C++ insert code

**Comment by genghisken** [comment]
It would be very useful to have the exact Flag Date & Time, but I can't implement this without at least week's downtime for ATLAS.  Likewise for Pan-STARRS.  Closing for the time being.
