### ISSUE TITLE
Possible list 'timeout' implementation

### ISSUE THREAD

**Issue by i-do-code-sometimes** [genghisken/ps1#113]
In order to prevent the possible list from becoming the ATLAS purgatory page (i.e. where objects are placed but a decision is never made to promote or trash either way), I'm proposing establishing some kind of timeout system for objects there. For instance, if an object gets moved to possible it has to be moved off of possible in six weeks, for the sake of argument, or else it is automatically junked (or moved to the attic, if tagged accordingly). Ideally, there should be enough time for ATLAS to get more data points for objects someone is unsure about while at the same time reducing the amount of junk on possible that won't benefit from more light curve data (e.g. bad subtractions).

**Comment by genghisken** [comment]
Having a second person on the eyeball rota to review the possible list has made this irrelevant now.  (Though the PS1 objects in Possible are indeed in purgatory.)
