### ISSUE TITLE
Button to produce an ATel with all fields filled automatically

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#118]
I've written a template ATel that we should start using now for all objects within 100 Mpc, or some other unusual interesting feature that we would like to announce, 

https://psweb.mp.qub.ac.uk/snegroupwiki/index.php/ATLAS_Astronomer%27s_Telegram_-_objects_within_100Mpc_or_unusual/bright

We can do this manually at first. But we need a button (or other solution, e.g. add to a custom list) 
that will produce the ATel text and insert the correct values accordingly.

**Comment by genghisken** [comment]
Done
