### ISSUE TITLE
ATLAS forced phot needs to reject outliers 

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#123]
There are too many of these getting through now to leave. It is causing trouble, in target selection, and the absolute mags at peak are way off, and causing confusion. 

Now have to fix 

Examples : 
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1024107930053339800/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1024107930053339800/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1055002160281312400/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1054247870242934900/

We know the diffs are rogue in this, and we need to reject these. There must be an easy way fro simple rejection of these points, from either the image FITS headers or the DDC files (e.g. I think the zeropoint is way off - which is  an easy catch). 

The diff images have obviously gone wrong, just from eyeballing. 

Look at the ZPs first to see if that's an easy rejection  as :

if ZP < 17 then reject

Taking a median or clipped median will not work since these are often single detections on a night with 3 or 4 upper limits. 

But we need to give this highest priority now 

Submitted to ATLAS and Marshall. Really an ATLAS problem but marshall is working with forced and averaging these mags, which is were it is really causing users difficulties.

**Comment by genghisken** [comment]
This is a non-trivial task that is being tackled outside of the ATLAS database.  Will implement inside the ATLAS interface once we have a good handle on the problem. Closing for the time being.
