### ISSUE TITLE
Galactic extinction link is broken - returns either no coordinates, the wrong RA (and sometimes the right coords)

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#128]
Examples (the current top 3 in the good list - but the wrong RA and the link not working is a common recurring problem) 

Returns the wrong RA: 
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1022219330120911300/

Links does not work : 
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1224952891401138400/

Works ok:
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1022338011431342800/

**Comment by genghisken** [comment]
Fixed.
