### ISSUE TITLE
Why in garbage ?

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#130]
Some manual checking with ZTF 

why was this put straight in garbage ? 

https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1045149891484021700/

**Comment by genghisken** [comment]
Diffs are done by subcell (1/64 of chip).  I have a piece of code that checks the number of objects in a diff subcell for the most recent set of detections.  If it's greater than a threshold number (currently set to 1000) 3 times, the object gets ditched.  In this case we had ~1600 objects in the offending cell when it was flagged.  This tool is very crude and we should scale the threshold with galactic latitude.  The object would not have passed until MJD58434.  FYI for each detection we got:

| MJD | cell_n_dets |
|---|---|
| 58432.503613 | 1642 |
| 58432.503613 | 1642 |
| 58432.503613 | 1642 |
| 58432.5086775 | 1602 |
| 58432.5086775 | 1602 |
| 58432.5086775 | 1602 |
| 58432.5096259 | 1550 |
| 58432.5096259 | 1550 |
| 58432.5210527 | 1766 |
| 58432.5210527 | 1766 |
| 58432.5210527 | 1766 |
| 58434.475321 | 1313 |
| 58434.475321 | 1313 |
| 58434.4897753 | 1099 |
| 58434.4897753 | 1099 |
| 58434.4976586 | 869 |
| 58434.4976586 | 869 |
| 58434.5091211 | 1025 |
| 58434.5091211 | 1025 |
| 58436.4836804 | 2532 |
| 58436.4836804 | 2532 |
| 58436.4990474 | 1851 |
| 58436.4990474 | 1851 |
| 58436.4990474 | 1851 |
| 58436.5057044 | 2053 |
| 58436.5057044 | 2053 |
| 58436.5156847 | 2087 |
| 58436.5156847 | 2087 |
| 58438.4660513 | 791 |
| 58438.4660513 | 791 |
| 58438.4797029 | 564 |
| 58438.4797029 | 564 |
| 58438.4865127 | 684 |
| 58438.4865127 | 684 |
| 58438.4865127 | 684 |
| 58438.4977843 | 430 |
| 58438.4977843 | 430 |
| 58442.4618161 | 473 |
| 58442.4618161 | 473 |
| 58442.4659574 | 765 |
| 58442.4659574 | 765 |
| 58442.4780308 | 527 |
| 58442.4891455 | 503 |
| 58442.4891455 | 503 |
| 58442.4891455 | 503 |
