### ISSUE TITLE
Sherlock offset distances sometimes calculated incorrectly  

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#137]
Sometimes physical distance calculation (when spec z known) is wrong by factor of 100 ! Angular distances are reported correctly, something wrong in the calc. 

Looks like this is an ATLAS interpretation of Sherlock problem - as Sherlock gets the calculation right  in PESSTO marshall, but wrong on ATLAS pages 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1130914640405438800/
http://www.pessto.org/marshall/transients/search?q=ATLAS19lsy

**Comment by genghisken** [comment]
I believe this is fixed now.  Closing.  Will open a new ticket if more examples are spotted.
