### ISSUE TITLE
Introduce GW event filtering to the Pan-STARRS pages and retrofit old page style GW filtering into ATLAS

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#141]
We need to introduce GW event filtering on Pan-STARRS pages so we quickly eyeball the objects of interest to us when a GW event happens.  It's already introduced into the ATLAS New Quickview pages (the ones that show the lightcurves as well) but we need to also retrofit the older style quickview and table view pages.

Pan-STARRS O3

https://star.pst.qub.ac.uk/sne/pso3/psdb/followup/2/?gwevent=190728

https://star.pst.qub.ac.uk/sne/pso3/psdb/followup_quickview/2/?gwevent=190728

Pan-STARRS 3PI

https://star.pst.qub.ac.uk/sne/ps13pi/psdb/followup/2/?gwevent=190728

https://star.pst.qub.ac.uk/sne/ps13pi/psdb/followup_quickview/2/?gwevent=190728

ATLAS

https://star.pst.qub.ac.uk/sne/atlas4/followup/5/?gwevent=190728

https://star.pst.qub.ac.uk/sne/atlas4/followup_quickview/5/?gwevent=190728

https://star.pst.qub.ac.uk/sne/atlas4/followup_quickview_bs/5/?gwevent=190728

**Comment by genghisken** [comment]
Implemented and rolled out.

**Comment by smarttgit** [comment]
Remind me what the time window is on this search

**Comment by thespacedoctor** [comment]
between (t0 - 10days) and (t0 + 21days)

**Comment by genghisken** [comment]
Those limits are hard-wired into Dave's tagging code, but it wouldn't be too difficult for me to return a subset of the GW data. (E.g. t=0-5 days -- gwevent=190728&t1=0&t2=5)

**Comment by genghisken** [comment]
Done.

**Comment by genghisken** [comment]
Note that the date filtering is still ongoing, but we'll start a new issue specifically for that.
