### ISSUE TITLE
Processing some stacked data with the new YSE database for stack-stack diffs

### ISSUE THREAD

**Issue by djones1040** [genghisken/ps1#156]
Now that the new database for stacked images is available, could ingest some of the data to see if anything can be discovered.

**Comment by genghisken** [comment]
OK. Apologies for the delay - I've been unwell this week.  Recovered now.

There were quite a few config issues to fix.  It's taken longer than I hoped (about 3 hours) to fix.  I've run all the data that Mark processed and just downloading images now.  Data are on the ps1ysestack database in the eyeball list.

https://star.pst.qub.ac.uk/sne/ps1ysestack/psdb/

Don't promote anything to "good" yet.  I haven't started the relevant name daemons.

216 objects made it through the pixel ML cuts, including "variable" stars (VS, BS).

**Comment by genghisken** [comment]
Still to fix - stacked forced photometry.  I need to do some minor code updates to make it compatible with stacked diffs.

**Comment by djones1040** [comment]
this is awesome!  mostly missed this last week, sorry.  should I tell the team to search soon?

**Comment by djones1040** [comment]
Hi Ken, talked about this briefly in our meeting yesterday.  We were wondering if it would be possible to get MJD ranges instead of some of the dates on the page so we know the dates covered by each stack?  And also if you'd be able to get the CSV files set up for good/possible.

**Comment by djones1040** [comment]
closing this, as the original issue is fixed, but going to open up a new issue for the CSV files/MJD ranges.  thanks Ken!
