### ISSUE TITLE
forced photometry isn't being run on the confirmed list (I think)

### ISSUE THREAD

**Issue by djones1040** [genghisken/ps1#160]
see https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1100247451033558300/, for example

**Comment by genghisken** [comment]
Well spotted!  It is now.

**Comment by djones1040** [comment]
thanks Ken!

**Comment by genghisken** [comment]
Ah - I also made an arbitrary decision after the downtime in March not to request any forced photometry for objects flagged before March 9th.  I'll move that back to at least January 1st.
