### ISSUE TITLE
YSE data for 2020jgl

### ISSUE THREAD

**Issue by djones1040** [genghisken/ps1#161]
Hi Ken - looks like the new YSE data for 2020jgl isn't getting read in.  Talked to Mark yesterday and I think this is because it's being observed on UH time - Mark said it's in the YSE datastore but the naming convention is different or something?

**Comment by genghisken** [comment]
Apologies! I meant to change the regular expression to pull down the UH exposures and got distracted.  I checked the datastore and I can see that UH tagged diffs started appearing on 21st May.  So I've reset the pointer on the datastore and it will catch up at some stage today.

**Comment by djones1040** [comment]
thanks!  closing this
