### ISSUE TITLE
some targets still without RB factors from yesterday

### ISSUE THREAD

**Issue by djones1040** [genghisken/ps1#164]
Hi Ken, a few things on the eyeball list w/o RB factors: https://star.pst.qub.ac.uk/sne/ps1yse/psdb/followup/4/
Thanks!

**Comment by genghisken** [comment]
Oops.  Recurrence of the image batch download issue.  I've raised another issue (#165) to do a formal investigation of the download problem (and to at least create code to mitigate the problem).  Have fixed the current batch and thus will close this issue.

**Comment by djones1040** [comment]
thanks!
