### ISSUE TITLE
Machine Learning integration

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#6]
Originally reported by: **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**

----------------------------------------

Darryl has created a first draft script that needs to be integrated into the general code.

Note tha the script should NOT run when the postage stamp server is downloading data.

The following tasks are required:

* Query the database for objects whose realbogus values are not set
* Facilitate the query to be run on a per object basis (so we can override the settings)
* Run the classifier on these objects, setting the RB values on the fly instead of writing a CSV file

----------------------------------------
- Bitbucket: https://bitbucket.org/genghisken/ps1/issue/6

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

The first draft ML code is now done, including Multiprocessing.  The following enhancements are necessary for full automation:

* Transfer the code to the 'pstc' user.  Make sure that it still runs OK with Ureka, etc.
* Make sure the code will run correctly on psdb2
* Add a call to this code at the end of the Multiprocessing postage stamp downloader.
* Add a call to the OTA Mapping code (New Ghost Checker) at the end of the Multiprocessing postage stamp downloader.
* Add code to move all objects below RB threshold value to the Garbage after the ML code has run.

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

First draft of the postage stamp wrapper is now complete.  Ureka installed for pstc user.  Runs OK on psdb2.  Calling from CRON presented an interesting challenge for the Ureka environment setup, but seems to work OK now.  Multiprocessing code now ditches objects if an RB Threshold is specified.  Wrapper script also calls ghost checker.

**Comment by smarttgit** [comment]
Complete !
