### ISSUE TITLE
Calculate and show limiting magnitudes on lightcurves

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#60]
Originally reported by: **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**

----------------------------------------

The Pan-STARRS limiting magnitude calculations are encoded in a table attached to the CMF catalogue files.  Fit an order 6 polynomial to this table and calculate 50% mark.  This is the limiting magnitude.

For ATLAS limiting mags are supplied in the header or in the forced photometry table.

For both PS1 and ATLAS, we should show the limiting mags on the lightcurves (unforced and forced).

For PS1 on a daily basis we need to calculate limiting mags for new ingested files and update the database (deteff_counts, deteff_calculated_offset, deteff_magref).

----------------------------------------
- Bitbucket: https://bitbucket.org/genghisken/ps1/issue/60

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

For PS1 we need to modify the getLightcurveBlanks and getLightcurveNonDetections and replace the static limits with the ones in the header if any of the header values are not null.  (Otherwise use the static values.)

For the GW code, we chose an arbitrary cutoff (COUNT_THRESHOLD) of 200 counts before we trust the calculated offset (otherwise the guessed offset was used)

The calculation if all deteff fields populated is:

limit = deteff_magref + 2.5 * log10(exptime) + ((deteff_counts > COUNT_THRESHOLD) ? deteff_calculated_offset : 0) + zero_pt

Note that this also requires:

* adding 3 new columns (deteff_counts, deteff_calculated_offset, deteff_magref) to tcs_cmf_metadata
* refreshing the django view of tcs_cmf_metadata
* adding the 3 columns to TcsCmfMetadata in models.py
* writing code to calculate the 3 values and populate the database (needs to be included into daily ingest framework)
* alteration of web code to use correct calculation (e.g. plain text code), hence alteration of lightcurve queries.

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

Draft version of calculation and DB update code is done.  GW database schema upgrade (but not web view or models.py yet).

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

Calculation for all 171,000 ingested GW files is done. Database updated.

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

Calculation for all 12 million ingested 3pi files is done. Database updated.

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

Code is now integrated into the daily ingest script.  Need to monitor to make sure this is functioning correctly.

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

Still to do:

* ps1ncu database
* ps1md database
* ps1ss database

Database schemas are updated, we just need to do a one-off calculation of the limits.

**Comment by smarttgit** [comment]
Done and superseded by forced phot
