### ISSUE TITLE
Broken PS1 lightcurve

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#63]
Originally reported by: **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**

----------------------------------------

Need to check this object.  Something up with the lightcurve.  Could be bad data that we need to deal with.

http://psweb.mp.qub.ac.uk/sne/ps13pi/psdb/candidate/1110106610142226900/

----------------------------------------
- Bitbucket: https://bitbucket.org/genghisken/ps1/issue/63

**Comment by smarttgit** [comment]
No common
