### ISSUE TITLE
Add code to render information from Sherlock Context

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#64]
Originally reported by: **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**

----------------------------------------

Need to add new web code tor read the database tables created for Sherlock.

Tables are:

* sherlock_crossmatches
* sherlock_classification

Updates required are:

* Create new sherlock tables, database views and django models
* Show sherlock summary comments on front page (can be done by updating summary stats)
* Show sherlock classification and annotations on candidate page
* Show context map (e.g. with Aladin Lite)

----------------------------------------
- Bitbucket: https://bitbucket.org/genghisken/ps1/issue/64

**Comment by smarttgit** [comment]
Good enough - comments and host object names. Not  a priority for changing Sherlock 2.0 done
