### ISSUE TITLE
Add code to render information about GW Events

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#65]
Originally reported by: **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**

----------------------------------------

We need to render information about gravity events on our GW pages.

To do this, we need to add:

* The 2 new gw tables, views and django models
* Modify the view.py code to collect the information from the tables
* Render the information on the candidate page - maybe as a comment at the top.

----------------------------------------
- Bitbucket: https://bitbucket.org/genghisken/ps1/issue/65

**Comment by smarttgit** [comment]
Done - breaker working, just a matter of ensuring it runs
