### ISSUE TITLE
Check if KEGS galaxies are cross-matched and can be flagged

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#8]
Originally reported by: **Stephen Smartt (Bitbucket: [sjsmartt](https://bitbucket.org/sjsmartt), GitHub: Unknown)**

----------------------------------------

Kepler has started the Campaign 4 on Feb 8:
RA = 03:56:18.2, Dec = +18:39:38.

The list of galaxies is attached. 

Can you check if this is being cross-matched against - with a radius of 30 arcsec. 
And if matches are found then add a flag in the "Nearest column.
Something like KEGS ####### (where the ######## is the number in first column of attached
table). Also leave the other cross-matches in there too.

----------------------------------------
- Bitbucket: https://bitbucket.org/genghisken/ps1/issue/8

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

OK.  I need to parse and load this catalog which should take me an hour.  The old code just flagged if the object was a kepler source at the beginning of the algorithm.  This is slightly more complicated, but do-able I think.  At the END of the algorithm we should do the kepler check and set a kepler flag.  (The object type is a bitmap. Setting the kepler flag will result in the object being called "kepler sn" or "kepler agn", etc.)  The daily stats code then needs to be modified to pick up the new flag in order to populate the column in the summary table.

**Comment by genghisken** [comment]
*Original comment by* **Ken Smith (Bitbucket: [genghisken](https://bitbucket.org/genghisken), GitHub: [genghisken](https://github.com/genghisken))**:

----------------------------------------

Have now moved to Kepler checks to the end of the crossmatch algorithm.  Current crossmatch radius set to 30 arcsec.  There's a bug in the crossmatch insertion code which currently means only the zeroth entry is added (currently the nearest matched object).  This means that any additional Kepler info is currently lost.  The fix is non-trivial, so at the moment the object will be flagged as of Kepler interest, but I'll need to do some manual checking to find out which Kepler object we matched against.  The fix will be to get the code to insert the NEAREST match for different catalogues.  One immediate fix I could do now is add JUST the Kepler info INSTEAD of the other match information.

**Comment by smarttgit** [comment]
Kepler finished
