### ISSUE TITLE
Mismatch between ATLAS and Sherlock classifications

### ISSUE THREAD

**Issue by katemaguire** [genghisken/ps1#83]
AT2018ub (ATLAS18mbv) and AT2018ts (ATLAS18mbu) were both discovered by ASSASN offset from the centre of host galaxies. Sherlock has them both as SNe but they ended up in the stars list in ATLAS. AT2018ub was associated with a stellar source found in the 2MASS PSC catalogue, which appears to be located in the galaxy (not sure if 2MASS classified the galaxy has a point source?).

I have promoted them to the good list since it doesn't look like the issue with AT2018qq where the ASASSN coordinates were off and it was actually a variable star. Not sure why AT2018ts ended up in the stars list.

**Comment by genghisken** [comment]
The algorithms are now aligned on both the Marshall and ATLAS.
