### ISSUE TITLE
Force 'discovering' ATLAS target with only one detection

### ISSUE THREAD

**Issue by katemaguire** [genghisken/ps1#84]
For AT2018tq (discovered by ASASSN), there is potentially one previous detection in ATLAS from 45 days. I assume it never got 'discovered' because it was a single detection (ATLAS 1124151561233043500 - https://star.pst.qub.ac.uk/sne/atlas4/candidate/1124151561233043500/)

Is there a way I can force it through? From the ASSASN data it looks young but combined with ATLAS would suggest otherwise.

**Comment by genghisken** [comment]
It would be interesting to see the images from the first "detection" to check that it's real.  The code will only trigger on 3+ detections.  I can modify the web code to allow users to manually trigger objects.  (I have a script that does it, but it would be useful if users could be able to trigger them via the web interface.)
