### ISSUE TITLE
A nearby galaxy fast-track eyeball list

### ISSUE THREAD

**Issue by thespacedoctor** [genghisken/ps1#86]
The plan is to bypass some/all threshold cuts to 'fast-track' sources associated with spectroscopic galaxies within 150 Mpc

- [x] @katemaguire asked how many SDSS spectroscopic galaxies are there within 150 Mpc?
- [x] Dave to add glade catalogue to Sherlock
- [x] Dave to come up with a sensible Sherlock algorithm to flag these transients 
- [x] Ken to create a new 'fast-track eyeball' list for users to prioritise the eyeballing of these sources

@smarttgit

**Comment by thespacedoctor** [comment]
There are:

- 73,237 **SDSS spectroscopic** galaxies within z = 0.035
- 19,888 galaxies within 150 Mpc in the **NED D catalogue**

**Comment by smarttgit** [comment]
How many in the GLADE catalogue ?

**Comment by thespacedoctor** [comment]
> The catalog has been constructed (combined and matched) from four existing galaxy catalogs: GWGC, 2MPZ, 2MASS XSC and HyperLEDA. Additionally, we have extended GLADE with the SDSS-DR12 quasar catalog. GLADE contains **3,262,883** objects.

I'm tidying up a couple of solar-system tasks and then I'll get this installed! 

Downloaded from [here](http://aquarius.elte.hu/glade/Download.html).

**Comment by smarttgit** [comment]
Need to talk about this - 3 million seems a lot.

**Comment by genghisken** [comment]
Ken to check that Sherlock is running against all the necessary NED sources for the eyeball list.  Otherwise we can't move to the fast track list

**Comment by thespacedoctor** [comment]
I ran a few queries on the current ATLAS4 database to try and get a handle of the number of sources we should expect to be added to the 'fast-track' eyeball list. The ATLAS4 database has been up and running since 2017-09-21 (176 days) and has notched up the following source counts:

| Cumulative Filtering  | Count | % of previous Filter |
| :------------ | :----------- | :----- |
| 1. Unique Objects with no cuts     | 1,240,169,263  | - |
| 2. Sources with Sherlock Classification (i.e. 3 or more 'good' detections)   | 9,183,924 | 0.7% |
| 3. Sources with non-stellar Sherlock Classification | 864,085 | 9.4% |
| 4. Source with RB Factor > 0.2 | 214,363 | 24.9% |
| 5. In galaxy within 100 Mpc (fast-tracked) | 2741 | 1.3% |

The average rate of sources being added to the eyeball list is therefore \~1200 objects/day and to the new fast-track list will be **\~16 objects/day**.

Of the 2741 sources that would have ended in the fast-track list, there would have been 1930 SN (70%) and 811 NT (30%).

The suggestion is to fast-track sources in galaxies within 100 Mpc just after step 3 so they're prioritised for stamp generation and machine learning before the rest of the sources that will eventually end up in the normal eyeball list.

Ken here's how I selected the sources for fast-track if it's useful ...

```sql
SELECT cl.transient_object_id
FROM
    sherlock_classifications cl,
    sherlock_crossmatches cm,
    atlas_diff_objects o
WHERE
		o.detection_list_id is not null
        AND cl.classification NOT IN ('VS' , 'BS', 'cv', 'AGN', 'orphan', 'unclear')
        AND cl.transient_object_id = cm.transient_object_id
        AND o.id = cl.transient_object_id
        AND photoZ is null
        AND rank = 1
        AND (direct_distance < 100 OR distance < 100);
```

**Comment by genghisken** [comment]
Fast track list is now implemented.  Still to do: Alter to force collection of stamps for the fast track list BEFORE the rest of the stamps.

**Comment by smarttgit** [comment]
Can we also get the objects which WERE fast tracked labelled on the good object page

**Comment by thespacedoctor** [comment]
think we're done here
