### ISSUE TITLE
Decommission psweb and migrate all host services to new virtual machine

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#87]
All services hosted by psweb urgently need to be moved to a new VM (currently called psweb2).  This is because psweb has an ongoing fault and the physical machine now needs to be decommissioned.  The space is also required in the rack by the new server.

The services include:

* All the mediawiki wikis (SNe Group Wiki, PSAT-LV-Wiki and the archived PESSTO wiki)
* All active Django web pages:
  - atlas3
  - atlas4
  - ps13pi
  - ps13pipublic
  - ps1fgss
  - ps1fgssold
  - ps1gw
  - ps1md
  - ps1ncu
  - ps1ss
* The Supernova Archive

Once this is complete, psweb will be deactivated and psweb2 will inherit the IP address of psweb.  There will also be minor proxy config issues on Star to deal with.

All the services have been migrated and tested.  (The archive is now physically located on dbstore4.)  Recording here so this task has visibility.  This issue will be closed once the server switch is done (which may necessitate one final rsync).

**Comment by katemaguire** [comment]
I'm trying to get on to ps13pi to look at an object: PS18gr but I get a proxy error. I can get to https://star.pst.qub.ac.uk/sne/ps13pi/psdb/ but none of the subpages ('good' list) are loading.

**Comment by genghisken** [comment]
Nothing to do with the migration.  Database was dumping and a rogue process tried to do an update.  Freed now.

**Comment by katemaguire** [comment]
OK good to hear. I can confirm I can access the page now.

**Comment by genghisken** [comment]
So - for some reason, I now get CSRF errors when trying to access ALL the Pan-STARRS pages (except the old MD pages) via star (the proxy server) but when accessing the server directly (star.pst -> psweb.mp) things work fine.  I've spent hours trying to diagnose this, but have got nowhere for now.  This problem DOES NOT affect the ATLAS pages, which sport the identical authentication code, which is even more mystifying.

**Comment by genghisken** [comment]
Just as I was going to bed, I figured it out.  I had to add a new setting to the ATLAS and old PS1 MD pages, which I forgot to propagate into the template settings file:

```CSRF_TRUSTED_ORIGINS = ['star.pst.qub.ac.uk']```
