### ISSUE TITLE
False positives in eyeballing

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#88]
All - we should not be sending obvious flare stars to TNS.  E.g.:
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1175638670203248700/
Object is clearly in the galactic plane, and PS1 stamp shows obvious red star at the position of the transient.  I've been placing these in the Attic, but I'm open to alternative suggestions about what we do with these.

Opened a new issue - since this is not a "missed object".

**Comment by smarttgit** [comment]
Clarification - 

these stellar variables must **not** go in the GOOD list.  The GOOD list gets sent to TNS. 

Yes, they should go in the ATTIC 

Sherlock has also misclassified them as SN as it pulls out a spurious NED cross-match, when it should be a star.  I will add an issue in Sherlock. But please, all, look carefully and do not promote clearly variable stars

**Comment by genghisken** [comment]
All - watch out for objects that have been crossmatched against very old surveys.  E.g.
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1145210910292706900/ = SSS130404-145211-292707 (i.e. discovered in April 2013 by CRTS).  Should be in the attic - almost certainly a CV.

See the right-most column in the tabular view of the data (in the followup lists) or the top of the candidate page "See also...".
