### ISSUE TITLE
Determine a way to stop junk lightcurve detections going to TNS as discovery date

### ISSUE THREAD

**Issue by genghisken** [genghisken/ps1#89]
Some objects are being promoted (correctly) that have junk detections ~ hundreds of days ago.  This results in a TNS name from the previous year (e.g. 2017) rather than the current year.  It also records a false discovery date on the TNS.

**Comment by genghisken** [comment]
E.g.:
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1045410450230944400/

**Comment by katemaguire** [comment]
Here is another one, first detection is a junk detection from January, AT2018bbo/ATLAS18nqm  https://star.pst.qub.ac.uk/sne/atlas4/candidate/1123932270072215800/

**Comment by katemaguire** [comment]
Another one: ATLAS18nfd/SN2017kat https://star.pst.qub.ac.uk/sne/atlas4/candidate/1150419071483650800/

**Comment by katemaguire** [comment]
ATLAS18nfv/AT2017kas https://star.pst.qub.ac.uk/sne/atlas4/candidate/1155909411350150000/

**Comment by genghisken** [comment]
We agreed that the solution now is to report the discovery date as the first of the 5 sigma detections on the night that the object was triggered.

**Comment by genghisken** [comment]
The TNS requires that we send the last "non-detection" as well as the first detection.  The code now reports the first 5 sigma detection on the trigger MJD. The last non-detection will now be reported as EITHER any previous detection (more than 0.5 days previously) OR the last non-detection (more than 0.5 days previously) - whichever is the most recent.  Hopefully this will now stop junk TNS discovery dates being reported.

**Comment by genghisken** [comment]
New object reported as old one by the TNS code again, in spite of the fix. Need to investigate how this one slipped through the net.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1021822170255424200/

**Comment by genghisken** [comment]
This is fixed now.  I have a sliding window that will not allow "old" detections to be reported to TNS.
