### ISSUE TITLE
Movers getting through

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#92]
Definite mover - why not caught ?

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1151340411414240200/

**Comment by smarttgit** [comment]
More 
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1151340771414238000/

**Comment by genghisken** [comment]
They're almost always comets.  They don't appear in the downloaded version of the MPC database, so I'm not yet sure how to exclude them.  The value of pmv is not always set for the detections, but for some detections it is set for this object.  We might be able to use the value of pmv for some detections to trigger a direct MPC check.  Both of these are the same (new-ish) comet C/2018 C2 (Lemmon).

**Comment by smarttgit** [comment]
Why not do direct MPC on all eyeball list. It is not so many

**Comment by genghisken** [comment]
That depends on your definition of "so many".  The MPC can cope with 10s or 100s of requests but no more.  If I send more they will block me.  Additionally, we are not running at full capacity at the moment because of the terrible weather.  Once we start getting 1000s of object in the eyeball list again, we will once more be blocked.  Furthermore, the interface is very slow, and can only be parallellized up to maybe 4 parallel threads.  Dave is working on code that may help me in this case in the future.

**Comment by thespacedoctor** [comment]
I have code now that might solve the problem. Ken can you remind me what your process is at the minute? Do you use pyephem then MPC?

**Comment by genghisken** [comment]
Yes - code uses (py)ephem, but only objects in the Good list are sent to MPC.  In most of my cases this is fine, but the comets are not in the MPC data dump.  (Note that objects (e.g. NEOs) with funny orbits almost certainly get rejected anyway because the detections will not get associated into single objects in ATLAS, so the granularity of pyephem is OK I think.)

**Comment by thespacedoctor** [comment]
I've sent you an invite to my Orbfitv5.0 fork that I hacked apart.

So I think the way to go is to:

1. Find all sources within 2 arcmin of the transient with pyephem
2. Refine all match locations with `ephem` command (good to 0.5'')
3. Rematch transient location with new refined solar-system body locations within your radius of choice.

---

# Orbfit v5.0.5 Fork

This is a 'fork' of the [Orbfit code found here](http://adams.dm.unipi.it/orbfit/). At the time I forked the code it was at v5.0.5.

The main contribution I've made is to craft an new executable called `ephem` that will generate an ephemeris for a single object, at a single epoch given a specific observatory code. This hacked/new code can be found in `/src/orbfit/ephem.f90`

I've also made a few minor modifications to the main body of code, including to increase the precision of many of the ephemeris outputs.

## [](https://github.com/thespacedoctor/Orbfit5.0-fork#installation)Installation

To install this fork of Orbfit, you should be able to clone this repo to your machine and then [follow these install instructions](http://psweb.mp.qub.ac.uk/dry//blog/2017/09/15/Installing-OrbFit-5.0-on-macOS.html)but using the code in this repo and not the code downloaded from the Orbfit distribution site.
    
    git clone git@github.com:thespacedoctor/Orbfit5.0-fork.git

## [](https://github.com/thespacedoctor/Orbfit5.0-fork#ephem-usage)ephem Usage
    
    usage:
       ephem <obscode> <mjd> <objectName>
    
       <obscode>:        observatory code (use 500 for geocentric)
       <mjd>:            the modified julian date of the ephemeris you wish to generate (UTC)
       <objectName>:     the ID of the asteroid you wish to generate an ephemeris for (MPC number or name)
    
    cmdline options:
    
      -h, --help        print usage information and exit

For example, to generate an ephemeris for asteroid `10547` from the ATLAS observatory at Haleakela on MJD `57916.0` run:
    
    $ ephem T05 57916.0 10547
    mjd,ra_deg,dec_deg,apparent_mag,observer_distance,heliocentric_distance,sun_obs_target_angle,phase_angle,galactic_latitude,ra_arcsec_per_hour,dec_arcsec_per_hour,object_name,obscode
    57916.000000,15.077432,2.039571,18.123,2.1104503,1.9411821,66.3842,28.6332,-60.7539,65.8674,26.0504,10547,T05

**Comment by genghisken** [comment]
Good job.  I can refine the ephems with your code, but my source database is still missing the comets (I think), so I can't look it up with your code.  But I see where you're headed here...
