### ISSUE TITLE
Delay in sending to TNS - missing discovery

### ISSUE THREAD

**Issue by smarttgit** [genghisken/ps1#93]
We flagged this on 

Flag Date: April 5, 2018

But it reached the TNS on 2018-04-06 17:52:02

Which caused the delay, and meant ASASSN got the discovery. 

Why are we seeing another delay ?

**Comment by smarttgit** [comment]
It is also not cross-matched against AT2018aqi

**Comment by genghisken** [comment]
Objects are given a Flag Date when the automated post-ingest code promotes the object.  The object will remain in the eyeball list until someone actually moves it into the good list.  Only when it's in the good list will it get registered on TNS.  In this case, the object was flagged on April 5, 2018, but not promoted until the early evening of April 6, 2018 (by Peter in fact).  ASASSN registered their object at 1am on April 6.

Additionally, I'm using the Marshall database to cross check with TNS entries, but as Dave has pointed out, there is currently a Marshall ingest problem.  Hence the lack of TNS crossmatch.

**Comment by genghisken** [comment]
Fixed by the eyeballing rota now.
